export { useGameStore, 
  selectPhase, 
  selectScore, 
  selectProgress,
  selectTimeRemaining,
  selectVinyls,
  selectSlots,
  selectDraggedVinyl,
  selectHoveredSlot,
  selectIsPlaying,
  selectIsPaused,
  selectIsGameOver,
} from './gameStore';
